language: go
sudo: false
go:
  - 1.12.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

env:
  - GO111MODULES=on

script:
  - go test -cover -coverprofile=coverage.txt -covermode="atomic" . -v

after_success:
- bash <(curl -s https://codecov.io/bash)